repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      # - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
  # - repo: local
  # hooks:
  #   - id: generate-devcontainer
  #     name: Generate DevContainer Dockerfile and devcontainer.json
  #     entry: devbox/precommit/gen_devcontainer.sh
  #     language: script
  #     pass_filenames: false
