# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .stateful_string import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "statefulString",
  "mod": "index",
  "fqn": "pulumi_statefulString",
  "classes": {
   "statefulString:index:StatefulString": "StatefulString"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "statefulString",
  "token": "pulumi:providers:statefulString",
  "fqn": "pulumi_statefulString",
  "class": "Provider"
 }
]
"""
)
