# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['StatefulStringArgs', 'StatefulString']

@pulumi.input_type
class StatefulStringArgs:
    def __init__(__self__, *,
                 string: pulumi.Input[str],
                 triggers: pulumi.Input[Mapping[str, pulumi.Input[str]]]):
        """
        The set of arguments for constructing a StatefulString resource.
        """
        pulumi.set(__self__, "string", string)
        pulumi.set(__self__, "triggers", triggers)

    @property
    @pulumi.getter
    def string(self) -> pulumi.Input[str]:
        return pulumi.get(self, "string")

    @string.setter
    def string(self, value: pulumi.Input[str]):
        pulumi.set(self, "string", value)

    @property
    @pulumi.getter
    def triggers(self) -> pulumi.Input[Mapping[str, pulumi.Input[str]]]:
        return pulumi.get(self, "triggers")

    @triggers.setter
    def triggers(self, value: pulumi.Input[Mapping[str, pulumi.Input[str]]]):
        pulumi.set(self, "triggers", value)


class StatefulString(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 string: Optional[pulumi.Input[str]] = None,
                 triggers: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 __props__=None):
        """
        Create a StatefulString resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: StatefulStringArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a StatefulString resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param StatefulStringArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(StatefulStringArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 string: Optional[pulumi.Input[str]] = None,
                 triggers: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = StatefulStringArgs.__new__(StatefulStringArgs)

            if string is None and not opts.urn:
                raise TypeError("Missing required property 'string'")
            __props__.__dict__["string"] = string
            if triggers is None and not opts.urn:
                raise TypeError("Missing required property 'triggers'")
            __props__.__dict__["triggers"] = triggers
        super(StatefulString, __self__).__init__(
            'statefulString:index:StatefulString',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'StatefulString':
        """
        Get an existing StatefulString resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = StatefulStringArgs.__new__(StatefulStringArgs)

        __props__.__dict__["string"] = None
        __props__.__dict__["triggers"] = None
        return StatefulString(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def string(self) -> pulumi.Output[str]:
        return pulumi.get(self, "string")

    @property
    @pulumi.getter
    def triggers(self) -> pulumi.Output[Mapping[str, str]]:
        return pulumi.get(self, "triggers")

